contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "Hugo-BeautifulHugo"
canonifyurls = true

baseurl = "/" #without ending slash
languageCode = "en-us"
title = "Prepper.fyi"

[params]
  twitterName = "Prepper_fyi"
  description = "Are you a prepper?"

     
  
  
