contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "Hugo-BeautifulHugo"
languageCode = "en-us"
#canonifyurls = true
#relativeURLs = true

baseurl = "https://www.prepper.fyi/" 
title = "Prepper.fyi"
copyright = "© 2016. All rights reserved."

[permalinks]
    post = "/:year/:month/:slug/"

[author]
	facebook = "Prepperfyi-1660307567619768/"
	twitter = "Prepper_fyi"

[[menu.main]]
    name = "Current Contest"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "contest"
    url = "http://win.prepper.fyi/lp/15680/lifestraw"

[[menu.main]]
    name = "Privacy"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
    identifier = "privacy"
    url = "/page/privacy"

[[menu.main]]
    name = "Terms"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    identifier = "terms"
    url = "/page/terms"

[params]
    logo = "/images/prepper.fyi.logo.300x157.jpg" 
    fbtype = "website"
    fbimage = "/images/prepper.fyi.logo.600x314.jpg"

[params.authors]
  [params.authors.Jon]
    "firstName"  = "Jon"
  
