contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "Hugo-BeautifulHugo"
canonifyurls = true

baseurl = "/" 
languageCode = "en-us"
title = "Prepper.fyi"

[author]
	facebook = "#"
	twitter = "Prepper_fyi"
	name = ""   
 
[[menu.main]]
    name = "Current Contest"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "contest"
    url = "http://win.prepper.fyi/lp/15680/lifestraw"

[[menu.main]]
    name = "Privacy"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
    identifier = "privacy"
    url = "/page/privacy"

[[menu.main]]
    name = "Terms"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    identifier = "terms"
    url = "/page/terms"


  
